ReadSpeaker.ui=function(){var a=null,f=[],m=[],x=!1,q=function(g){g=g||window.event;g.returnValue=!1;if(g=g.originalEvent)g.cancelBubble=!0,g.returnValue=!1;g&&g.preventDefault&&g.preventDefault();g&&g.stopPropagation&&g.stopPropagation()},l=function(){rspkr.log("[rspkr.ui] Attempting to add click events.");var g=$rs.get("."+rspkr.ui.rsbtnClass+" .rsbtn_play"),a=null;$rs.isArray(g)||(g=[g]);for(var b=0,c=g.length;b<c;b++)if($rs.unregEvent(g[b],"click",ReadSpeakerDefer.clickhandler),a=g[b]?$rs.getAttr(g[b],
"data-rsevent-id"):"_bogus_",rspkr.l.f.eq.store[a]&&rspkr.l.f.eq.store[a].click)rspkr.log("[rspkr.ui] Click event already existed on "+g[b],2);else{$rs.regEvent(g[b],"click",function(h){q(h);window.readpage(this)});rspkr.ui.addFocusHandler(g[b],!0,g[b].parentNode);rspkr.log("[rspkr.ui] Added click event to: "+g[b],1);try{$rs.getAttr(g[b],"role")||$rs.setAttr(g[b],"role","button")}catch(f){rspkr.log("[rspkr.ui] Could not add role attribute.",2)}}},y=function(){rspkr.log("[rspkr.ui] Initiating global callbacks");
rspkr.ui.rsbtnClass=rspkr.cfg.item("ui.rsbtnClass")||"rsbtn";window.readpage=function(g,a){if(rspkr.ui.initrun){if(/ios|ipad|iphone|ipod|android/i.test(window.navigator.userAgent)){var b=window.rspkr;b.audio=new Audio;b.audio.play();b.audio.pause()}rspkr.ui.showPlayer(g,a)}};window.rshlexit=function(g){rspkr.HL.chunking&&rspkr.HL.chunking.destroy();(void 0===g||"false"===g)&&a.stop();setTimeout(function(){rspkr.c.dispatchEvent("onAfterSyncExit",window)},1E3)};window.rshlinit=p().sync.init;window.rshlsetContent=
p().sync.setContent;window.rshlsetId=p().sync.setId;window.rshlsync=function(g,a){for(var b=g.split(","),c=a.split(","),h=0,n=g.length;h<n;h++)p().sync.execute(b[h],c[h])};window.rshlcontinue=function(){function g(h){if(!rspkr.HL.chunking.entracte.src){var h=encodeURIComponent(decodeURIComponent(rs.cfg.getPhrase(h))),a={},b;for(b in rspkr.c.data.params)rspkr.c.data.params.hasOwnProperty(b)&&(a[b]=rspkr.c.data.params[b]);b=rspkr.Common.data.selectedText;var c=rspkr.Common.data.selectedHTML;rspkr.Common.data.selectedText=
h;rspkr.Common.data.selectedHTML="";a.text=h;a.output="audio";h=rspkr.c.buildReadSpeakerCall(a);rspkr.HL.chunking.entracte.src=h;rspkr.Common.data.selectedText=b;rspkr.Common.data.selectedHTML=c}rspkr.HL.chunking.entracte.volume=parseFloat((rspkr.st.get("hlvol")||100)/100);rspkr.HL.chunking.entracte.play()}if(rspkr.HL.chunking){rspkr.log("[rspkr.ui.rshlcontinue]");rspkr.HL.chunking.chunkEnded=!0;var a=$rs.get("#sync"+rspkr.HL.html5.synclist[rspkr.HL.html5.synclist.length-1][2]),a=$rs.offset(a);if(rspkr.HL.chunking.continueHref){var b=
rspkr.cfg.item("cb.chunking.pause",void 0,!0);if(-1==rspkr.HL.chunking.continueTime)if(rspkr.log("[rspkr.ui.rshlcontinue] Waiting for user interaction"),rs.ui.getActivePlayer().pause(),$rs.addClass(rspkr.ui.getActivePlayer().getContainer(),"rsautopaused"),g("chunkcontinue"),b&&"function"==typeof b)rspkr.log("[rspkr.ui.rshlcontinue] Running custom callback",3),b();else{rspkr.log("[rspkr.ui.rshlcontinue] Showing default continue button");b=document.createElement("div");b.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");
$rs.addClass(b,rspkr.ui.rsbtnClass+" rspopup rsresume");var c=$rs.findIn(b,"a");c.removeAttribute("href");$rs.regEvent(c,"click",function(){rspkr.c.dispatchEvent("onChunkResume",window)});$rs.findIn(c,".rsbtn_text").innerHTML="<span>"+rs.cfg.getPhrase("chunkbutton")+"</span>";document.body.appendChild(b);b.style.display="block";a.left+=15;c=a.left+$rs.width(b)-$rs.width(window);0<c&&(a.left-=c);b.style.left=a.left+"px";b.style.top=a.top+15+"px"}else 0==rspkr.HL.chunking.continueTime?(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay"),
rspkr.c.dispatchEvent("onChunkResume",window)):isNaN(rspkr.HL.chunking.continueTime)?rspkr.log("[rshlcontinue] Invalid time parameter!",3):(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay with "+rspkr.HL.chunking.continueTime+" seconds delay"),5<=rspkr.HL.chunking.continueTime&&g("chunkwait"),b&&"function"==typeof b&&b(rspkr.HL.chunking.continueTime),rspkr.HL.chunking.stall=!0,setTimeout(function(){rspkr.HL.chunking.stall=!1},1E3*rspkr.HL.chunking.continueTime),rspkr.HL.chunking.timer=setTimeout(function(){rspkr.c.dispatchEvent("onChunkResume",
window)},1E3*rspkr.HL.chunking.continueTime))}else rspkr.log("[rshlcontinue] No continue href found!")}};var g=rspkr.c.data.browser;g&&(/iphone|ipad|ios|android/i.test(g.OS)||"android"==g.name.toLowerCase())?($rs.regEvent(document.body,"touchstart",function(g){rspkr.ui.setPointerPos(g);return!0}),$rs.regEvent(document.body,"touchend",function(g){rspkr.ui.setPointerPos(g);rspkr.c.data.setSelectedText(g);return!0}),$rs.regEvent(document,"selectionchange",function(g){rspkr.c.data.setSelectedText(g);
return!0})):($rs.regEvent(document.body,"mousedown",function(g){rspkr.ui.setPointerPos(g);return!0}),$rs.regEvent(document.body,"mouseup",function(a){"opera"===g.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(window,"mouseup",function(a){"opera"===g.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(document.body,"keydown",rspkr.ui.setPointerPos),
$rs.regEvent(document.body,"keyup",function(g){rspkr.c.data.setSelectedText(g);return!0}))},v=function(){document.removeEventListener?document.removeEventListener("click",window.ReadSpeakerDefer.clickhandler,!1):document.detachEvent&&document.detachEvent("onclick",window.ReadSpeakerDefer.clickhandler);if(ReadSpeakerDefer.deferred){var g=ReadSpeakerDefer.deferred,a=null;if("a"!=g.tagName.toLowerCase()){for(a=g;"body"!=a.tagName.toLowerCase()&&!(a=a.parentNode,"a"==a.tagName.toLowerCase()););g=a}ReadSpeakerDefer.isRSLink(g)&&
(rspkr.log("[rspkr.ui] Activating deferred element: "+g),$rs.removeClass(g.parentNode,"rsdeferred"),rspkr.ui.showPlayer(g));ReadSpeakerDefer.deferred=null}},r=null,e=function(){r&&$rs.isVisible(r)&&(rspkr.log("[rspkr.ui.updateFocus] "+r.outerHTML),t(r))},t=function(g){$rs.focus&&("function"==typeof $rs.focus&&g)&&$rs.focus(g)},b=function(g){if("iconon"==rspkr.st.get("hlicon")&&!x){var a=m.push(new j)-1;m[a].id=a;m[a].show(g);x=!0}},c=function(){"iconon"==rspkr.st.get("hlicon")&&x&&(m.pop().hide(),
x=!1)},j=function(){var g=0,a=0,b=null,c=52,f=null,h=null,n=null,e=function(g){g=g||b;$rs.addClass(g,rspkr.ui.rsbtnClass+" rspopup");rspkr.cfg.item("general.useCompactPopupButton")&&$rs.addClass(g,"rscompact")},j=function(g){$rs.unregEvent(b,"mouseout",i);window.clearTimeout(f);var a,c=b.clientWidth+10,u;h=rspkr.ui.showPlayer(n,b,!0);u=h.getWidth();a=parseInt($rs.offset(b).left);if((a=rspkr.ui.viewport.width+$rs.scrollLeft(document)-a)<u)a=parseInt($rs.css(b,"left"))-(u-(c-10)),$rs.css(b,"left",a+
"px");x=!1;$rs.unregEvent(n,"click",j);$rs.regEvent(n,"click",function(g){q(g);return h.restart()});q(g);return!1},i=function(){f||(f=window.setTimeout(function(){p()},rspkr.cfg.item("general.popupCloseTime")||2E3))},k=function(){f&&(window.clearTimeout(f),f=null)},l=function(g,a){var h=document.body.getBoundingClientRect();$rs.css(b,{top:a-h.top+"px",left:g-h.left+"px",width:c+"px"})},p=function(){$rs.css(b,{display:"none",top:0,left:0});k();m.splice(null,1);x=!1;b.parentElement.removeChild(b)},
w=rspkr.c.findFirstRSButton(),b=document.createElement("div");b.id=rspkr.getID();b.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");e();n=$rs.findIn(b,".rsbtn_play");$rs.setAttr(n,"href",w?$rs.getAttr(w,"href"):null);(w=rspkr.cfg.item("general.popupHref"))&&$rs.setAttr(n,"href",w);var w=$rs.getAttr(n,"href").match(/lang=([^&;]*)/i).pop(),z=$rs.findIn($rs.get(b),".rsbtn_play span.rsbtn_text span");z&&(z.textContent=z.innerText=rspkr.cfg.getPhrase("listen",w,"en_us"));$rs.setAttr(n,"title",rspkr.cfg.getPhrase("listentoselectedtext",
w,"en_us"));$rs.regEvent(n,"click",j);document.body.appendChild(b);return{setPos:l,show:function(h){k(h);if(h&&"none"==$rs.css(b,"display")){var n=b.cloneNode(!0);n.id=rspkr.getID();$rs.css(n,{display:"block",position:"absolute",top:0,left:0});document.body.appendChild(n);c=$rs.outerWidth(n)+3;document.body.removeChild(n);n=h.clientX||h.pageX||rspkr.ui.pointerX;h=h.clientY||h.pageY||rspkr.ui.pointerY;a=h>rspkr.ui.pointerY?h-$rs.scrollTop(document)+36>rspkr.ui.viewport.height-46?h-66:h+30:10>h-$rs.scrollTop(document)-
66?h+30:h-51;g=10>n-$rs.scrollLeft(document)?n+10:n-$rs.scrollLeft(document)>rspkr.ui.viewport.width-(c+10)?rspkr.ui.viewport.width+$rs.scrollLeft(document)-(c+10):n+0;l(g,a)}$rs.regEvent(b,"mouseout",i);$rs.regEvent(b,"mouseover",k);i(null);e();$rs.css(b,"display","block")},hide:p,id:null}},i={update:function(g,b,c){"hlspeed"===g&&b!==c&&(g=g.replace("hl",""),rspkr.c.converter[g]&&"function"==typeof rspkr.c.converter[g]&&(b=rspkr.c.converter[g](b)),rspkr.c.data[g]=b,a&&a.stop(),rspkr.pl.releaseAdapter())}},
k=function(g,a,b,c,f,h){$rs.css(g,"background-color","rgb("+a+","+b+","+c+")");c<f?(c+=10,window.setTimeout(function(){k(g,a,b,c,f,h)},50)):h&&"function"===typeof h&&h.apply(g,[])},p=function(){return rspkr.XP?rspkr.XP:rspkr.HL};_expand=function(g){"string"==typeof g&&(g=$rs.get(g));$rs.isArray(g)||(g=[g]);for(var a=0;a<g.length;a++)rspkr.ui.Player(g[a]).show(!0)};_animate=function(){var a=rs.cfg.item("ui.animate");if(a){var b,c=15,f=500;"object"==typeof a?(a.id&&(b=$rs.get(a.id)),a.count&&(c=a.count),
a.interval&&(f=a.interval)):"string"===typeof a&&(b=$rs.get(a));if("boolean"===typeof a&&a||$rs.isArray(b)&&0==b.length||!b)b=$rs.get("."+rs.ui.rsbtnClass);$rs.isArray(b)||(b=[b]);var e=c,h=setInterval(function(){0==e&&($rs.removeClass(b,"rsanimate"),clearInterval(h));1==e--%2?$rs.addClass(b,"rsanimate"):$rs.removeClass(b,"rsanimate")},f)}};return{meta:{revision:"3798"},initrun:!1,init:function(){var a=rspkr.Common.addEvent;a("onAfterModsLoaded",y);a("onReady",l);a("onReady",v);a("onReady",_animate);
a("onSelectedText",b);a("onDeselectedText",c);a("onSettingsChanged",i.update);a("onAfterSyncInit",e);this.initrun=!0;rspkr.Common.dispatchEvent("onUIInitialized");rspkr.log("[rspkr.ui] Initialized!")},addFocusHandler:function(a,b,c){var f=b,e=c,e=e||a;void 0===f&&(f=!0);$rs.focusIn&&"function"==typeof $rs.focusIn&&($rs.focusIn(a,function(){$rs.addClass(e,"rsfocus");!0===f&&(r=a);rspkr.Common.dispatchEvent("onFocusIn",window,[a,e])}),$rs.focusOut(a,function(){$rs.removeClass(e,"rsfocus");rspkr.Common.dispatchEvent("onFocusOut",
window,[a,e])}))},focus:function(a){t(a)},updateFocus:function(){e()},showOverlay:function(b,c){var f=b,e;e=c||a.getContainer();var j=$rs.findIn(e,".rsbtn_status");0===j.length&&(j=document.createElement("span"),j.className="rsbtn_status_overlay",j.innerHTML='<span class="rsbtn_status"></span>',$rs.findIn(e,".rsbtn_exp").appendChild(j),j=$rs.findIn(e,".rsbtn_status"));$rs.css($rs.findIn(e,".rsbtn_status_overlay"),"display","block");if("nosound"===f)f='<a class="rsbtn_nosound">'+rspkr.cfg.getPhrase("nosound")+
"</a>",j.innerHTML=f,(f=$rs.findIn(e,".rsbtn_nosound"))&&$rs.regEvent(f,"click",function(){return a.nosound()});else if("loaderror"===f){var f=rspkr.c.data.getSaveData("link"),h=document.createElement("a");h.className="rsbtn_loaderror";h.innerHTML="[?]";h.href=f;$rs.regEvent(h,"click",function(a){rspkr.ui.Lightbox.show("<iframe src='"+h.href+"' style='height:100%'></iframe>",null,!1,null,300);q(a)});j.innerHTML=rspkr.cfg.getPhrase("loaderror")||"An error has occurred, try again";j.appendChild(h)}else j.innerHTML=
f},settings:i,rsbtnClass:"",addClickEvents:function(){l()},initGlobalCallbacks:function(){y()},showPopupIcon:function(a){b(a)},processDeferred:function(){v()},showPlayer:function(b,c,e){var j;a:{var i=e;rspkr.log("[rspkr.ui.showPlayer]");i=i||!1;if("string"==typeof b)b:{for(var e=$rs.get("a"),h=0,n=e.length;h<n;h++)if(e[h].href&&e[h].href==b){e=e[h];break b}e=!1}else e=b;e=(h=e)?$rs.closest(h,".rsexpanded"):void 0;e=$rs.hasClass(e,"pre-expanded")?void 0:e;n=rspkr.HL.chunking?rspkr.HL.chunking.currentChunkNumber:
1;if(e&&!$rs.isArray(e)&&rspkr.ui.getActivePlayer()&&1==n&&rspkr.ui.getActivePlayer().getContainer()==e)rspkr.log("Player already active, calling Player.restart() instead"),rspkr.ui.getActivePlayer().restart(),j=void 0;else{rspkr.HL.chunking&&rspkr.HL.chunking.destroy();rspkr.HL.chunking&&rspkr.HL.chunking.html5support&&(rspkr.HL.chunking.entracte=new Audio,rspkr.HL.chunking.entracte.play(),rspkr.HL.chunking.entracte.pause());rspkr.c.dispatchEvent("onBeforeParamsSet",window,[h]);e="string"==typeof b?
b:$rs.getAttr(h,"href");n=null;"string"==typeof b&&(b=e.match(/readid=[^&]+/gi),n=e.match(/readclass=[^&]+/gi),b&&0<b.length&&rspkr.HL.Restore.Storage.readId.push(b[0].replace("readid=","").split(",")),n&&0<n.length&&rspkr.HL.Restore.Storage.readClass.push(n[0].replace("readclass=","").split(",")));rspkr.c.data.selectedHTML="";rspkr.c.data.setParams(e);void 0!==$rs.getAttr(h,"data-target")&&null!==$rs.getAttr(h,"data-target")&&(b=$rs.getAttr(h,"data-target"),b=$rs.get(b),"object"===typeof b&&(c=b));
c&&!i?(n=$rs.get(c),$rs.addClass(n,rspkr.ui.rsbtnClass+" rsfloating"),rspkr.basicMode&&($rs.removeClass(n,"rshidden"),$rs.addClass(n,rspkr.ui.rsbtnClass+" rsvisible"))):n=$rs.closest(h,"div."+rspkr.ui.rsbtnClass);if(!0===rspkr.cfg.item("survey.allowed"))if(c=rspkr.c.cookie,i=rspkr.cfg.item("survey.cookieName")||"rspkrsurvey",b=rspkr.cfg.item("survey.cookieLifetime")||15552E6,h=rspkr.c.data.params,"1"===c.readKey(i,"nmbrdisplays")){rspkr.ui.Lightbox.show(rspkr.cfg.item("survey.url")+"?customerid="+
h.customerid+"&lang="+h.lang,rspkr.st.r().replaceTokens(rspkr.cfg.item("ui.survey.buttons").join(),{rsSURVEY_BUTTON_CLOSErs:rspkr.cfg.getPhrase("close")}),!0,function(){$rs.regEvent($rs.get("#rssurvey_button_close"),"click",rspkr.u.Lightbox.hide)},500);rspkr.log(c.updateKey(i,"nmbrdisplays","displayed",b),4);j=void 0;break a}else void 0===c.readKey(i,"nmbrdisplays")&&rspkr.log(c.updateKey(i,"nmbrdisplays","1",b),4);b:{c=n;for(j in f)if(f[j]&&f[j].getContainer&&f[j].getContainer()==c){j=f[j];break b}j=
new rspkr.ui.Player(c);f.push(j)}if(a&&a!=j||a&&e!==a.getHref())a.close(!0),rspkr.c.dispatchEvent("onUIClosePlayer",a.getContainer(),[0<rspkr.c.data.selectedText.length?"textsel":"nosel"]);c=(c=a)?c.getID():null;rspkr.c.dispatchEvent("onUIShowPlayer",window,[c,j.getID()]);j.setHref(e);a=j;j.show();j=a}}return j},expand:function(a){_expand(a)},pointerX:0,pointerY:0,setPointerPos:function(a){a.pageX&&(rspkr.ui.pointerX=a.pageX);a.pageY&&(rspkr.ui.pointerY=a.pageY);a.originalEvent&&(a.originalEvent.touches&&
a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageX)&&(rspkr.ui.pointerX=a.originalEvent.touches[0].pageX);a.originalEvent&&(a.originalEvent.touches&&a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageY)&&(rspkr.ui.pointerY=a.originalEvent.touches[0].pageY);return!0},viewport:{width:$rs.width(window),height:$rs.height(window)},popups:m,hl:function(a,b){window.setTimeout(function(){k(a,255,255,100,255,b)},200)},scroll:{INTERVAL:null,STEPS:25,scrollToElm:function(a){$rs.isVisible(a)&&
this.initScroll(a)},scrollToAnchor:function(a){for(var b=$rs.get("a"),c=null,e=0;e<b.length;e++){var f=b[e];if(f.name&&f.name==a){c=f;break}}this.initScroll(c)},initScroll:function(a){if(a){for(var b=a.offsetTop,c=a;c.offsetParent&&c.offsetParent!=document.body;)c=c.offsetParent,b+=c.offsetTop;b-=50;rs.cfg.item("ui.autoscrollOffset")&&!isNaN(rs.cfg.item("ui.autoscrollOffset"))&&(b-=rs.cfg.item("ui.autoscrollOffset"));clearInterval(rspkr.u.scroll.INTERVAL);var c=rspkr.u.scroll.getCurrentYPos(),e=parseInt((b-
c)/rspkr.u.scroll.STEPS);rspkr.u.scroll.INTERVAL=setInterval(function(){rspkr.u.scroll.scrollWindow(e,b,a)},10)}else document.location.hash=a},getCurrentYPos:function(){return document.body&&document.body.scrollTop?document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:window.pageYOffset?window.pageYOffset:0},scrollWindow:function(a,b,c){var e=rspkr.u.scroll.getCurrentYPos(),f=e<b;window.scrollTo(0,e+a);a=rspkr.u.scroll.getCurrentYPos();
if(f!=a<b||e==a)window.scrollTo(0,b),clearInterval(rspkr.u.scroll.INTERVAL),"string"==typeof c&&(location.hash=c)}},activePlayer:a,getActivePlayer:function(){return a}}}();
ReadSpeaker.ui.Slider=function(){var a=this,f={handleClass:"",width:0,height:0,left:0,top:0,steps:-1,stepsize:-1,dir:"h",initval:-1,drop:null,start:null,dragging:null,click:null,labelDragHandle:"",labelStart:"",labelEnd:"",nudge:1},m={rsid:void 0,parent:void 0,ref:void 0},x=void 0,q=void 0,l=void 0,y=void 0,v=void 0,r=!1,e=0,t=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()};
this.initElement=function(a){if(!r){"string"==typeof a&&(a=document.getElementById(a));a.innerHTML+='<a href="javascript:void(0);" role="slider" class="keyLink" style="display:block; border:0;">&#160;</a>';var c=a.getElementsByTagName("a"),c=c[c.length-1],j=-1<f.steps?f.steps:100;c.relatedElement=a;$rs.setAttr(c,"title",f.labelDragHandle);$rs.setAttr(c,"aria-label",f.labelDragHandle);$rs.setAttr(c,"aria-orientation","h"==f.dir?"horizontal":"vertical");$rs.setAttr(c,"aria-valuemin",0);$rs.setAttr(c,
"aria-valuemax",j);$rs.setAttr(c,"aria-valuenow",f.initval||0);e=f.initval;$rs.regEvent(a,"mousedown",this.startDragMouse);$rs.regEvent(c,"click",function(a){t(a)});$rs.regEvent(c,"keyup",this.startDragKeys);$rs.regEvent(c,"dragstart",function(a){t(a)});$rs.regEvent(a,"touchstart",this.touchStart);$rs.regEvent(m.parent,"mousedown",this.mouseClick)}};this.mouseClick=function(b){if(!r&&!$rs.hasClass(m.ref,"dragged")){var c=a.findPos(b.target),e=b.clientX-(c.left-f.left),b=b.clientY-(c.top-f.top);l=
c.left;y=c.top;c=a.getCurrentVal({left:e,top:b});"function"==typeof f.click&&f.click(c,m);return!1}};this.findPos=function(a){var c=curTop=0;if(a.offsetParent){do c+=a.offsetLeft,curTop+=a.offsetTop;while(a=a.offsetParent);return{left:c,top:curTop}}};this.startDragMouse=function(b){rspkr.log("[rspkr.ui.Slider] startDragMouse");if(!r){a.startDrag(this);var c=b||window.event;x=c.clientX;q=c.clientY;$rs.regEvent(document.body,"mousemove",a.dragMouse);$rs.regEvent(document.body,"mouseup",a.releaseElement)}t(b);
return!1};this.startDragKeys=function(b){rspkr.log("[rspkr.ui.Slider] startDragKeys "+(b||window.event).keyCode);a.startDrag(this.relatedElement);$rs.regEvent(document.body,"keydown",a.dragKeys);$rs.regEvent(document.body,"keypress",a.switchKeyEvents);$rs.addClass(this.relatedElement,"rskeycontrolled");t(b)};this.touchStart=function(b){b=b.originalEvent;rspkr.log("[rspkr.ui.Slider] touchStart");r||(a.startDrag(b.target),x=b.touches[0].pageX,q=b.touches[0].pageY,$rs.regEvent(b.target,"touchmove",a.touchMove),
$rs.regEvent(b.target,"touchend",a.releaseElement));return!1};this.startDrag=function(b){rspkr.log("[rspkr.ui.Slider] startDrag");v&&a.releaseElement();l=b.offsetLeft;y=b.offsetTop;v=b;$rs.addClass(v,"dragged");"function"==typeof f.start&&f.start(m)};this.dragMouse=function(b){b=b||window.event;a.setPosition(b.clientX-x,b.clientY-q);a.valueChanged=!0;return!1};this.touchMove=function(b){b=b.originalEvent?b.originalEvent:b;t(b);a.setPosition(b.touches[0].pageX-x,b.touches[0].pageY-q);a.valueChanged=
!0;return!1};this.dragKeys=function(b){switch((b||window.event).keyCode){case 37:case 63234:a.valueChanged=!0;e-=f.nudge;break;case 38:case 63232:a.valueChanged=!0;e+=f.nudge;break;case 39:case 63235:a.valueChanged=!0;e+=f.nudge;break;case 40:case 63233:a.valueChanged=!0;e-=f.nudge;break;case 13:case 27:return a.releaseElement(),!1;case 9:return a.releaseElement(),!0;default:return rspkr.log("[rspkr.ui.Slider] return TRUE"),!0}!0===a.valueChanged&&(rspkr.c.dispatchEvent("onUISliderMove"),"function"==
typeof f.dragging&&f.dragging(a.getCurrentVal({skipValueCalculation:!0}),m));t(b);rspkr.log("[rspkr.ui.Slider] ready to return!");return!1};this.setPosition=function(b,c){var e,i=!1;e=b;var k=l,p=f.left,g=f.width,u="left";"v"==f.dir&&(e=c,k=y,p=f.top,g=f.height,u="top");e=k+e;-1<f.stepsize&&((e+p)%f.stepsize?e=f.stepsize*Math.ceil(e/f.stepsize)+p:i=!0);e>g+p?e=g+p:e<p&&(e=p);i||(v.style[u]=e+"px","function"==typeof f.dragging&&f.dragging(a.getCurrentVal(),m))};this.switchKeyEvents=function(){$rs.unregEvent(document.body,
"keydown",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.regEvent(document.body,"keypress",a.dragKeys)};this.releaseElement=function(){rspkr.log("[rspkr.ui.Slider] releaseElement");$rs.unregEvent(document.body,"mousemove",a.dragMouse);$rs.unregEvent(document.body,"mouseup",a.releaseElement);$rs.unregEvent(document.body,"keypress",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(v,"touchmove",
a.touchMove);$rs.unregEvent(v,"touchend",a.releaseElement);$rs.removeClass(v,"dragged");$rs.removeClass(v,"rskeycontrolled");$rs.removeClass(v,"rsmousecontrolled");var b=a.getCurrentVal();v=null;"function"==typeof f.drop&&!0===a.valueChanged&&f.drop(b,m);a.valueChanged=!1;rs.ui.getActivePlayer()&&rs.ui.getActivePlayer().setProgress();return!1};this.getCurrentVal=function(a){var c,j=f.width;c="left";var i=f.left;"v"==f.dir&&(j=f.height,c="top",i=f.top);var k=-1<f.steps?f.steps:100,j=-1<f.stepsize?
f.stepsize:j/k,a=a?a[c]:$rs.css(m.ref,c).replace(/px/i,"");pos=Math.round(a)-i;c=Math.round(pos/j);"v"==f.dir&&(c=k-c);rspkr.log("[rspkr.ui.Slider] currentval: "+c);return a&&a.skipValueCalculation||isNaN(c)?e=Math.max(Math.min(e,k),0):e=c};return{init:function(b,c){"string"==typeof b&&(b=document.getElementById(b));if(b){var e=b.id||"data-readspeaker-slider-id-"+Math.floor(2E4*Math.random());b.setAttribute&&b.setAttribute("data-readspeaker-slider-id-","data-readspeaker-slider-parent-"+e);var i={width:function(){return $rs.width(b)},
height:function(){return $rs.height(b)}};if("object"==typeof c)for(var k in c)c.hasOwnProperty(k)&&void 0!==f[k]&&(f[k]=c[k]);k=!1;var l;"rsbtn_volume_slider"===b.className&&("jquery"===rspkr.l.f.currentLib()&&1.5>parseFloat(jQuery.fn.jquery))&&(l=b.parentNode.style.display,b.parentNode.style.display="block",k=!0);f.width=i.width();f.height=i.height();k&&(b.parentNode.style.display=l);-1<f.steps&&(f.stepsize=("h"==f.dir?f.width:f.height)/f.steps);i=document.createElement("span");i.setAttribute("data-readspeaker-slider-id-",
e);i.className=f.handleClass||"rsbtn_progress_handle rsimg";b.appendChild(i);m.rsid=e;m.parent=b;m.ref=i;e=$rs.css(i,"left");null!==e&&(f.left=parseInt(e.replace(/px/i,"")));e=$rs.css(i,"top");null!==e&&(f.top=parseInt(e.replace(/px/i,"")));-1<f.initval&&this.jumpTo(f.initval);f.labelStart&&(e=document.createElement("span"),e.className="slider-label-start",e.innerHTML=f.labelStart,b.appendChild(e));f.labelEnd&&(e=document.createElement("span"),e.className="slider-label-end",e.innerHTML=f.labelEnd,
b.appendChild(e));a.initElement(i)}},jumpTo:function(a){if(isNaN(a))return!1;var c=101,e=a;-1<f.steps&&(a=Math.round(a),c=f.steps+1);if(-1<a&&a<c){var i=f.width,k=f.left,l="left";"v"==f.dir&&(i=f.height,k=f.top,l="top",a=c-1-a);m.ref.style[l]=i/(c-1)*a+k+"px";$rs.setAttr($rs.findIn(m.ref,"a.keyLink"),"aria-valuenow",e)}},setCurrentValue:function(a){e=a},getInstance:function(){return m},getContainer:function(){return m.parent},releaseElement:function(){a.releaseElement()},startDragKeys:function(b,
c){a.startDragKeys.call(b,c)},disabled:function(){if(arguments)r=arguments[0];else return r}}};
ReadSpeaker.ui.Player=function(a){var f=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},m=rspkr.getID(),x=this,q=[],l=0,y=!1,v=null,r=!1,e={_play:null,_pause:null,_stop:null,_vol:null,_settings:null,_dl:null,_closer:null,_powered:null,_get:function(b,c){var e,b="_"+b;e=a?this[b]&&0<this[b].length?this[b]:this[b]=$rs.findIn(a,c):null;return e==[]?null:e},play:function(){return this._get("play",
".rsbtn_play")},pause:function(){return this._get("pause",".rsbtn_pause")},stop:function(){return this._get("stop",".rsbtn_stop")},vol:function(){return this._get("vol",".rsbtn_volume")},settings:function(){return this._get("settings",".rsbtn_settings")},dl:function(){return this._get("dl",".rsbtn_dl")},pin:function(){return this._get("pin",".rsbtn_pin")},powered:function(){return this._get("powered",".rsbtn_powered")},closer:function(){return this._get("closer",".rsbtn_closer")},nosound:function(){return this._get("nosound",
".rsbtn_nosound")},setPlayPause:function(a){rspkr.log("[rspkr.ui.Player.setPlayPause("+a+")]");a=a?$rs.getAttr(this.pause(),"data-rsphrase-play"):$rs.getAttr(this.pause(),"data-rsphrase-pause");$rs.setAttr(this.pause(),"title",rspkr.c.decodeEntities(a));$rs.findIn(this.pause(),".rsbtn_btnlabel").innerHTML=a}},t=!1,b=[],c={play:function(){rspkr.c.dispatchEvent("onUIBeforePlay");rspkr.log("[rspkr.ui.handlers.play]");b.progress&&b.progress.disabled(!1);c.setStateClass(a,"rsplaying");rspkr.basicMode&&
c.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsplaying");$rs.addClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");e.setPlayPause(!1);if(rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().getContainer()==a)rspkr.pl.play(),r&&rspkr.pl.getProgress.apply(rspkr.pl,[!0,i,x]),rspkr.c.addEvent("onBeforeSyncInit",function(){r=!0;rspkr.pl.getProgress.apply(rspkr.pl,[!0,i,x])}),"flash"===rspkr.pl.adapter&&!rspkr.displog.onVolumeAdjusted&&rspkr.pl.setVolume(parseInt(rspkr.st.get("hlvol")||"100")),
rspkr.c.dispatchEvent("onUIAfterPlay"),rspkr.cfg.execCallback("cb.ui.play",a);else{rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().close();var h=$rs.findIn(a,".rsbtn_play");window.readpage(h)}},pause:function(){rspkr.log("[rspkr.ui.handlers.pause]");c.setStateClass(a,"rspaused");rspkr.basicMode&&c.setStateClass($rs.findIn(a,".rsbtn_exp"),"rspaused");e.setPlayPause(!0);rspkr.pl.pause();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIPause");rspkr.cfg.execCallback("cb.ui.pause",a);rspkr.log("ReadSpeaker.ui.pause")},
stop:function(){rspkr.log("[rspkr.ui.handlers.stop]");b.progress&&b.progress.disabled(!0);c.setStateClass(a,"rsstopped");$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");rspkr.basicMode&&c.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped");e.setPlayPause(!0);$rs.setAttr(a,"data-readspeaker-current",0);b.progress&&(b.progress.jumpTo(0),j(0));rspkr.pl.stop();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIStop",a);rspkr.cfg.execCallback("cb.ui.stop",a);(!document.getElementById("rslightbox_contentcontainer")||
!$rs.isVisible(document.getElementById("rslightbox_contentcontainer")))&&e.pause().focus();rspkr.HL.chunking&&1<rspkr.HL.chunking.currentChunkNumber&&(rspkr.HL.chunking.destroy(),rspkr.pl.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter());rspkr.log("ReadSpeaker.ui.stop")},setStateClass:function(a,b){a&&($rs.removeClass(a,"rspaused rsstopped rsplaying"),$rs.addClass(a,b))},vol:function(c){var e=$rs.findIn(a,".rsbtn_volume_container"),g=$rs.findIn(a,".rsbtn_volume"),c=c.originalEvent,f=function(a){var b=
a.originalEvent,b=$rs.closest(b.srcElement||b.originalTarget,".rsbtn_volume_container");if("click"===a.type){if(void 0===b||$rs.isArray(b)&&!b.length)$rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f)}else"keyup"===a.type&&27===a.keyCode&&($rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f))};$rs.css(e,"left",g.offsetLeft+"px");$rs.css(e,"display","none"==$rs.css(e,"display")?"block":"none");
"block"===$rs.css(e,"display")?($rs.regEvent(document.body,"click",f),$rs.regEvent(document.body,"keyup",f)):($rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f));c&&c.stopPropagation&&c.stopPropagation();c.cancelBubble=!0;g={keyCode:13};c=$rs.findIn(e,".keyLink");try{b.vol.startDragKeys(c,g)}catch(j){rspkr.log("[rspkr.ui.handlers.vol] Error accessing object _sliders['vol']")}return!1},settings:function(){$rs.hasClass(a,"rsplaying")&&this.pause();rspkr.ui.Lightbox.show(rspkr.st.getHTML(),
rspkr.st.getButtons(),!0,function(a){var b=$rs.get("rslightbox_closer"),c=function(){document.removeEventListener?b.removeEventListener("click",c,!1):document.detachEvent&&document.detachEvent("onclick",c);rspkr.c.dispatchEvent("onSettingsClosed",window,[])};$rs.regEvent(b,"click",c);rspkr.ui.addClickEvents();rspkr.c.dispatchEvent("onSettingsLoaded",window,[]);rspkr.cfg.execCallback("cb.ui.settingsopened",a)})},close:function(h){c.pin(!0);var h=h||!1,g=rspkr.pl,f=!1;rspkr.HL.chunking&&rspkr.HL.chunking.destroy();
h||rspkr.cfg.execCallback("cb.ui.beforeclose",a);g.hasOwnProperty("getProgress")&&rspkr.pl.getProgress(!1);g.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter();$rs.setAttr(a,"data-readspeaker-current",0);b.progress&&(b.progress.jumpTo(0),j(0));$rs.removeClass(a,"rsstopped rsplaying rspaused rsexpanded");if(rspkr.basicMode){var i;(i=$rs.findIn(a,".rsbtn_play"))&&$rs.removeClass(i,"rsexpanded")}$rs.hasClass(a,"rsfloating")&&($rs.removeClass(a,rspkr.ui.rsbtnClass),rspkr.basicMode&&($rs.removeClass(a,
"rsvisible"),$rs.addClass(a,"rshidden")));e.setPlayPause(!0);$rs.hasClass(a,"rspopup")&&(f=!0,$rs.removeClass(a,"rspopup"),$rs.css(a,"display","none"),a.parentNode.removeChild(a));$rs.css(a,"width","auto");delete rspkr.displog.onVolumeAdjusted;h||(rspkr.c.dispatchEvent("onUIClosePlayer",a,["userclick"]),rspkr.cfg.execCallback("cb.ui.close",a),rspkr.log("ReadSpeaker.ui.close: "+a));!h&&!1===f&&rspkr.ui.focus($rs.findIn($rs.get(a),".rsbtn_play"))},dl:function(){$rs.hasClass(a,"rsplaying")&&this.pause();
var b=$rs.getAttr($rs.findIn(a,".rsbtn_play"),"href"),c=b?rspkr.c.data.getSaveData("dialog",b):rspkr.c.data.getSaveData("dialog"),e=!1;rspkr.log("[rspkr.ui.handlers.dl] Savelink: "+c);rspkr.u.Lightbox.show(this.getDlDialog(),this.getDlButtons(),!0,function(){var a=$rs.get("#rsdl_button_accept"),b=$rs.get("#rsdl_button_decline");a&&$rs.regEvent(a,"click",function(b){rspkr.u.Lightbox.hide(b);e="iOS"!==rspkr.c.data.browser.OS&&0<rspkr.c.data.selectedHTML.length?!0:"iOS"!==rspkr.c.data.browser.OS&&!0===
rspkr.cfg.item("general.usePost")?!0:!1;if(!0===e){b=null;if(document.getElementById("dliframe"))b=document.getElementById("dliframe");else{if(document.selection)try{b=document.createElement('<iframe name="dliframe">')}catch(h){b=document.createElement("iframe")}else b=document.createElement("iframe");b.name="dliframe";b.setAttribute("id","dliframe");b.setAttribute("style","display: none; position: absolute;");b.style.display="none";var g=document.getElementsByTagName("body"),f=null;0<g.length&&(f=
g.item(0));if(f)f.appendChild(b);else return}b.src=c;return!1}$rs.setAttr(a,"href",c);return!0});b&&($rs.regEvent(b,"click",function(a){f(a);rspkr.u.Lightbox.hide(a)}),setTimeout(function(){rspkr.ui.focus(b)},200));rspkr.c.dispatchEvent("onDownloadLoaded",window,[])})},pin:function(b,c){var g=a.id+"_pinnedHome",f=document.getElementById(g),c=!c?!1:!0;if(!$rs.hasClass(e.pin(),"pinned")&&!b){if($rs.addClass(e.pin(),"pinned"),!f){var j=function(a,b){return window.getComputedStyle?window.getComputedStyle(a)[b]:
a.currentStyle?a.currentStyle[b]:a.style[b]},f=$rs.clone(a,!1,!0),i=a.offsetLeft,l=a.offsetTop;if(!c){f.style.width=j(a,"width").replace(/[^-\d\.]/g,"")-2+"px";f.style.height=j(a,"height").replace(/[^-\d\.]/g,"")-2+"px";for(var k="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),p=0,z;z=k[p];p++){var m=$rs.css(a,z);$rs.setAttr(a,"data-css-"+z,m);m=j(a,z);"auto"!=m&&(f.style[z]=m)}f.className="rsbtn_pinnedHome rsbtn";for(f.id=g;f.hasChildNodes();)f.removeChild(f.lastChild);
a.parentElement.insertBefore(f,a)}a.style.position="fixed";a.style.top=l-$rs.scrollTop(document)+"px";a.style.left=i-$rs.scrollLeft(document)+"px"}}else if($rs.hasClass(e.pin(),"pinned")||b)if($rs.removeClass(e.pin(),"pinned"),f){f.parentNode.removeChild(f);k="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" ");for(p=0;z=k[p];p++)m=$rs.getAttr(a,"data-css-"+z),$rs.css(a,z,m)}},getDlDialog:function(){var a=rspkr.cfg.item("ui.dldialog").join("\n"),b={};b.rsTERMS_OF_USE_HEADINGrs=
rspkr.cfg.getPhrase("touheading");b.rsTERMS_OF_USE_BODYrs=rspkr.cfg.getPhrase("toubody");return rspkr.st.r().replaceTokens(a,b)},getDlButtons:function(){var a=rspkr.cfg.item("ui.dlbuttons").join("\n"),b={};b.rsTERMS_OF_USE_ACCEPTrs=rspkr.cfg.getPhrase("touaccept");b.rsTERMS_OF_USE_DECLINErs=rspkr.cfg.getPhrase("toudecline");return rspkr.st.r().replaceTokens(a,b)},nosound:function(){var a=rspkr.c.data.getSaveData("link");$rs.setAttr(e.nosound(),"href",a);return!0}},j=function(b){var b=100<b?100:b,
c=$rs.findIn(a,".rsbtn_progress_played");"object"===typeof c&&$rs.css(c,"width",b+"%");rspkr.cfg.execCallback("cb.ui.progresschanged",a,[b])},i=function(c){if(c.length){var e=parseInt(c[0]),c=parseInt(c[1]),f=0==c?0:Math.round(100*(e/c)),g=$rs.findIn(a,".rsbtn_current_time"),i=$rs.findIn(a,".rsbtn_total_time"),l,p;b.progress&&(b.progress.setCurrentValue(f),t||(b.progress.jumpTo(f),j(f),g&&(g.innerHTML=l=k(e)),i&&(i.innerHTML=p=k(c)),rspkr.cfg.execCallback("cb.ui.timeupdated",a,[l,p])));rspkr.log("[rspkr.player.updateProgress] current time: "+
e+" total time: "+c);$rs.setAttr(a,"data-readspeaker-current",e);$rs.setAttr(a,"data-readspeaker-buffered",c);0<e&&$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading")}},k=function(a){var a=a/1E3,b=parseInt(a%60),c=parseInt(a/60%60),a=parseInt(a/60/60%60);return(10>a?"0"+a:a.toString())+":"+(10>c?"0"+c:c.toString())+":"+(10>b?"0"+b:b.toString())},p=function(){t=!0},g=function(b){rspkr.log("_dropProgress ("+b+")",5);b&&(b=b/100*$rs.getAttr(a,"data-readspeaker-buffered")/1E3,rspkr.pl.setProgress(b));
t=!1},u=function(a){g(a)},B=function(c){rspkr.log("_dropVolume, "+c,5);c=0>c?0:20*c;b.vol&&b.vol.jumpTo(c/20);rspkr.pl.setVolume(c);rspkr.st.set("hlvol",c);rspkr.cfg.execCallback("cb.ui.volumechanged",a,[c]);return!1},C=function(c,e){if("keyLink"===c.className){var f="";$rs.hasClass(e,"rsbtn_volume_handle")?f="vol":$rs.hasClass(e,"rsbtn_progress_handle")&&(f="progress");var g={keyCode:13};b[f].startDragKeys(c,g)}else $rs.hasClass(e,"rsbtn_volume")&&(g={keyCode:13},f=$rs.findIn(a,".rsbtn_volume_container"),
f=$rs.findIn(f,".keyLink"),b.vol.startDragKeys(f,g))},A=function(a,c){if("keyLink"===a.className){var e="";$rs.hasClass(c,"rsbtn_volume_handle")?e="vol":$rs.hasClass(c,"rsbtn_progress_handle")&&(e="progress");b[e].releaseElement();t=!1}};return{init:function(){q.push([this.show,[]])},initVolume:function(){if(!$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))){var c=rspkr.cfg,e=rspkr.st.get("hlvol")||"100",e=5*(parseInt(e)/100);b.vol=new rspkr.ui.Slider;b.vol.init($rs.findIn(a,".rsbtn_volume_slider"),
{handleClass:c.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:c.item("ui.volumeDir")||"v",steps:5,nudge:1,initval:e,dragging:B,click:B,labelDragHandle:c.getPhrase("slidervolumedesc")});c=$rs.findIn($rs.get(a),".rsbtn_volume_handle a");ui.addFocusHandler(c,!1,c.parentNode)}},show:function(h){var h=h?!0:!1,j=$rs.hasClass(a,"rsexpanded");$rs.rsid(a);a.id=m=a.id||rspkr.getID();ui=rspkr.ui;$rs.hasClass(a,rspkr.ui.rsbtnClass)||$rs.addClass(a,rspkr.ui.rsbtnClass);var i=null,i=rspkr.cfg,k=
rspkr.cfg.getPhrases(rspkr.c.data.getParam("lang"));if(0==$rs.findIn(a,".rsbtn_exp").length){var q=$rs.hasClass(a,"rspopup")?i.item("ui.popupplayer"):i.item("ui.player"),i=document.createElement("div");i.className="rsbtn_exp rsimg rspart";i.innerHTML+=q.join("\n");a.appendChild(i)}i=e.pin();q="Explorer"==rspkr.c.data.browser.name&&8>rspkr.c.data.browser.version;$rs.isArray(i)&&0==i.length&&(i=void 0);i&&!q&&rspkr.cfg.item("ui.usePin")?$rs.removeClass(i,"turnedOff"):i&&i.parentElement.removeChild(i);
if(k){i=function(a,b){var c=$rs.findIn(a,".rsbtn_btnlabel");$rs.isArray(c)||(c=[c]);0<c.length&&(c[0].innerHTML=b)};e.pause()&&($rs.setAttr(e.pause(),"data-rsphrase-pause",k.pause),$rs.setAttr(e.pause(),"data-rsphrase-play",k.play),$rs.setAttr(e.pause(),"title",rspkr.c.decodeEntities(k.pause)),i(e.pause(),rspkr.c.decodeEntities(k.pause)));e.stop()&&($rs.setAttr(e.stop(),"title",rspkr.c.decodeEntities(k.stop)),i(e.stop(),rspkr.c.decodeEntities(k.stop)));e.vol()&&($rs.setAttr(e.vol(),"title",rspkr.c.decodeEntities(k.volume)),
i(e.vol(),rspkr.c.decodeEntities(k.volume)));e.settings()&&($rs.setAttr(e.settings(),"title",rspkr.c.decodeEntities(k.settings)),i(e.settings(),rspkr.c.decodeEntities(k.settings)));e.dl()&&($rs.setAttr(e.dl(),"title",rspkr.c.decodeEntities(k.download)),i(e.dl(),rspkr.c.decodeEntities(k.download)));if(e.powered()){var q=$rs.findIn(e.powered(),".rsbtn_btnlabel"),v=k.speechenabled.match(/.*href="([^"]*)"/i).pop(),r=k.newwindow,x=document.createElement("p");x.innerHTML=k.speechenabled;r=(x.innerText||
x.textContent)+(r?" ("+r+")":"");q&&(q.innerHTML=k.speechenabled);$rs.setAttr(e.powered(),"title",r);$rs.setAttr(e.powered(),"data-readspeaker-href",v);q=$rs.getAttr(e.powered(),"data-rsevent-id");(!q||rs.l.f.eq.store[q]&&!rs.l.f.eq.store[q].click)&&$rs.regEvent(e.powered(),"click",function(){window.open($rs.getAttr(this,"data-readspeaker-href"))})}e.closer()&&($rs.setAttr(e.closer(),"title",rspkr.c.decodeEntities(k.closeplayer)),i(e.closer(),rspkr.c.decodeEntities(k.closeplayer)))}k=rspkr.c.data.browser;
(!/safari/i.test(k.name)||!/iphone|ipad|ios/i.test(k.OS))&&$rs.addClass(a,"rs-no-touch");k=$rs.findIn(a,".rsbtn_status_overlay");$rs.isArray(k)||$rs.css(k,"display","none");"fallback"===rspkr.pl.adapter&&(rspkr.ui.showOverlay("nosound",a),$rs.addClass(a,"rsstopped"));$rs.addClass(a,"rsexpanded");if(rspkr.basicMode){var w;(w=$rs.findIn(a,".rsbtn_play"))&&$rs.addClass(w,"rsexpanded")}!y&&!j&&(e.stop()&&($rs.regEvent(e.stop(),"click",function(a){f(a);c.stop()}),ui.addFocusHandler(e.stop())),e.pause()&&
($rs.regEvent(e.pause(),"click",function(b){f(b);$rs.hasClass(a,"rsplaying")?c.pause():($rs.hasClass(a,"rsstopped")||$rs.hasClass(a,"rspaused"))&&c.play()}),ui.addFocusHandler(e.pause())),e.closer()&&($rs.regEvent(e.closer(),"click",function(a){f(a);c.close()}),ui.addFocusHandler(e.closer())),e.vol()&&($rs.regEvent(e.vol(),"click",function(a){f(a);c.vol(a)}),ui.addFocusHandler(e.vol())),e.dl()&&($rs.regEvent(e.dl(),"click",function(a){f(a);return c.dl(a)}),ui.addFocusHandler(e.dl())),e.settings()&&
($rs.regEvent(e.settings(),"click",function(a){f(a);c.settings()}),ui.addFocusHandler(e.settings())),e.pin()&&($rs.regEvent(e.pin(),"click",function(a){f(a);c.pin()}),ui.addFocusHandler(e.pin())),w=rspkr.cfg,$rs.setAttr(a,"data-readspeaker-current",0),$rs.setAttr(a,"data-readspeaker-buffered",0),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_progress_container"))||(b.progress=new rspkr.ui.Slider,b.progress.init($rs.findIn($rs.get(a),".rsbtn_progress_container"),{handleClass:w.item("ui.progressHandleClass")||
"rsbtn_progress_handle rsimg",dir:w.item("ui.progressDir")||"h",nudge:5,start:p,dragging:g,click:u,labelDragHandle:w.getPhrase("sliderseek")}),j=$rs.findIn($rs.get(a),".rsbtn_progress_handle a"),ui.addFocusHandler(j,!1,j.parentNode)),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))||(j=rspkr.st.get("hlvol")||"100",j=5*(parseInt(j)/100),b.vol=new rspkr.ui.Slider,b.vol.init($rs.findIn(a,".rsbtn_volume_slider"),{handleClass:w.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:w.item("ui.volumeDir")||
"v",steps:5,nudge:1,initval:j,dragging:B,click:B,labelDragHandle:w.getPhrase("slidervolumedesc")}),j=$rs.findIn($rs.get(a),".rsbtn_volume_handle a"),ui.addFocusHandler(j,!1,j.parentNode)),rspkr.Common.addEvent("onFocusIn",C),rspkr.Common.addEvent("onFocusOut",A),rspkr.cfg.execCallback("cb.ui.open",a),y=!0);if($rs.findIn(a,".rsbtn_powered")&&(w=$rs.findIn(a,".rsbtn_powered .rsbtn_btnlabel a")))(/Chrome|Safari|Opera/gi.test(rs.c.data.browser.name)||/Explorer/gi.test(rs.c.data.browser.name)&&8<=rs.c.data.browser.version)&&
$rs.regEvent(w,"click",function(a){f(a)}),w.innerHTML='<span class="rsbtn_label_read">Read</span><span class="rsbtn_label_speaker">Speaker</span><span class="rsbtn_label_icon rsimg"></span>';"0"!=$rs.getAttr(a,"data-readspeaker-current")&&(rspkr.pl.releaseAdapter(),$rs.setAttr(a,"data-readspeaker-current",0));"fallback"!==rspkr.pl.adapter&&!h?(c.play(),rspkr.ui.focus(e.pause())):(b.progress&&b.progress.disabled(!0),c.setStateClass(a,"rsstopped"),$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),
"rsloading"),rspkr.basicMode&&c.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped"));h=(h=a)||a;h=$rs.clone(h,!0,!0);h.id=rspkr.getID();document.body.appendChild(h);$rs.css(h,{position:"absolute",top:"0",left:"0",display:"block",width:"auto"});$rs.css(h,"float","none");$rs.addClass(h,"rsexpanded");w=$rs.outerWidth(h)+3;h.style.display="none";document.body.removeChild(h);l=w;isNaN(l)||$rs.css(a,"width",l+(/[Ee]xplorer/.test(ReadSpeaker.c.data.browser.name)?1:0)+"px");$rs.hasClass(a,"rspopup")&&(!rspkr.cfg.item("ui.pinnedPopup")&&
!rspkr.basicMode)&&c.pin(!1,!0)},close:function(a){c.close(a)},stop:function(){c.stop()},nosound:function(){return c.nosound()},pause:function(){c.pause()},play:function(){c.play()},dl:function(a){c.dl(a)},settings:function(){c.settings()},vol:function(a){c.vol(a)},pin:function(a,b){c.pin(a,b)},restart:function(){rspkr.log("[rspkr.ui.restart]");c.stop();window.setTimeout(function(){c.play()},500);return!1},updateProgress:function(a){i(a)},setProgress:function(a){g(a)},getContainer:function(){return a},
getID:function(){return m},getWidth:function(){return l},setHref:function(a){v=a},getHref:function(){return v}}};
ReadSpeaker.ui.Lightbox=function(){var a=null,f=null,m=null,x=null,q=null,l=null,y,v=[],r=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},e=function(){var a=$rs.css(l,"display");$rs.css(l,"display","none");var b=$rs.height(window),e=$rs.height(document),f=parseInt($rs.css(document.documentElement,"width")),p=$rs.width(document),g=$rs.absOffset(document.body),m=
0,r=0;isNaN(f)&&(f=$rs.width(window));g.left&&(r=g.left);g.top&&(m=g.top);$rs.css(q,{width:(p>f?p:f)+"px",height:(e>b?e:b)+"px",top:"-"+Math.abs(m)+"px",left:"-"+Math.abs(r)+"px"});$rs.css(l,"display",a);t()},t=function(){var a=$rs.outerWidth(l),b=$rs.outerHeight(l),e=$rs.width(window),f=$rs.height(window),b=y+80+50<f?y+80:f-50;l.style.height=b+"px";$rs.get("#rslightbox_content").style.height=b-80+"px";b>f?(l.style.top=$rs.scrollTop(document)+"px",l.style.marginTop="10px"):(l.style.top=f/2+"px",l.style.marginTop=
-(b/2-$rs.scrollTop(document))+"px");a>e?(l.style.left=$rs.scrollLeft(document)+"px",l.style.marginLeft="0"):(l.style.left="50%",l.style.marginLeft=-(a/2-$rs.scrollLeft(document))+"px")},b=function(a){27===a.keyCode&&rspkr.ui.Lightbox.hide()};return{init:function(){var b=rspkr.pub.Config;a=b.item("ui.overlay.overlayStyles");f=b.item("ui.overlay.contentStyles");m=b.item("ui.overlay.contentTemplate");document.querySelectorAll||(d=document,s=d.createStyleSheet(),d.querySelectorAll=function(a,b,c,e,f){f=
d.all;b=[];a=a.replace(/\[for\b/gi,"[htmlFor").split(",");for(c=a.length;c--;){s.addRule(a[c],"k:v");for(e=f.length;e--;)f[e].currentStyle.k&&b.push(f[e]);s.removeRule(0)}return b});rspkr.log("[rspkr.ui.Lightbox] Heartbeat!")},show:function(c,j,i,k,p){for(var g=0,u=document.body.getElementsByTagName("*"),t;t=u[g];g++)-1!=t.tabIndex&&(v.push([t,t.tabIndex]),t.tabIndex=-1);if(!("Explorer"==rs.c.data.browser.name&&6==rs.c.data.browser.version)){t=document.querySelectorAll("body > *");for(g=0;u=t[g];g++)if(!("rslightbox_overlay"==
u.id||"rslightbox_contentcontainer"==u.id||"script"==u.tagName.toLowerCase())){var C=u.getAttribute("aria-hidden");C&&u.setAttribute("data-original-aria-hidden",C);u.setAttribute("aria-hidden","true")}}c=c||"";i=i||!1;q?(q.style.display="",l.style.display=""):(q=document.createElement("div"),q.id="rslightbox_overlay",l=document.createElement("div"),l.id="rslightbox_contentcontainer",l.innerHTML=rspkr.st.r().replaceTokens(m.join("\n"),{rsLIGHTBOX_CLOSE_LABELrs:rspkr.cfg.getPhrase("close")}),$rs.setAttr(q,
"style",a.join(";")),$rs.setAttr(l,"style",f.join(";")),document.body.appendChild(q),document.body.appendChild(l),rspkr.evt("onSettingsLoaded",{func:rspkr.st.r().handlers.changed.addButtonEvents,context:rspkr.st.r().handlers.changed,params:[this]}));g=$rs.get("rslightbox_closer");rspkr.ui.addFocusHandler(g,!1);$rs.regEvent(g,"click",function(a){r(a);rspkr.ui.Lightbox.hide(a)});$rs.regEvent(q,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(document.body,"keyup",b);if((u=document.documentElement)&&document.all)u.style.overflowX=
u.style.overflowY="hidden";if(c!=x||i)i=rspkr.cfg.getPhrase("close"),$rs.setAttr(g,"title",i),$rs.findIn(g,".rsbtn_btnlabel").innerHTML=i,$rs.get("#rslightbox_content").innerHTML="",$rs.css("#rslightbox_content","height","auto"),/^http/i.test(c)?$rs.findIn("#rslightbox_content","iframe").length||(i=document.createElement("iframe"),i.src=c,i.className="rslightbox-iframe",void 0===p&&(p=2E3),$rs.get("#rslightbox_content").appendChild(i)):"<"==c.substr(0,1)&&($rs.get("#rslightbox_content").innerHTML=
c),$rs.get("#rslightbox_buttons").innerHTML=j,x=c,"ar_ar"==rs.c.data.params.lang&&(-1==l.className.indexOf("rtl")&&(l.className=(l.className+" rtl").replace(/^\s+|\s+$/g,"")),$rs.setAttr($rs.findIn(l,"legend"),"align","right"));y=void 0!==p&&!isNaN(p)?p:!rspkr.basicMode?$rs.get("#rslightbox_content").clientHeight:$rs.get("#rslightbox_content").scrollHeight;c=$rs.findIn("#rslightbox_content",".rsform-row");for(g=0;g<c.length;g++){j=$rs.findIn(c[g],"input, a, select");$rs.isArray(j)||(j=[j]);for(u=
0;u<j.length;u++)rspkr.ui.addFocusHandler(j[u],!1,c[g])}var A=$rs.findIn("#rslightbox_buttons",".rssettings-button-close");rspkr.ui.addFocusHandler(A,!1);$rs.regEvent(A,"click",function(a){r(a)});(c=$rs.findIn("#rsform_wrapper",".rssettings-button-gotobottom"))&&!$rs.isArray(c)&&rspkr.ui.addFocusHandler(c,!1);(c=$rs.findIn("#rslightbox_buttons",".rssettings-button-gototop"))&&!$rs.isArray(c)&&rspkr.ui.addFocusHandler(c,!1);var h=$rs.findIn("#rslightbox_content","input");$rs.isArray(h)&&0<h.length?
setTimeout(function(){rspkr.ui.focus(h[0]);rspkr.Common.addEvent("onFocusIn",function(a){a.className&&$rs.hasClass(a,"rssettings-button-gototop")?rspkr.ui.focus(h[0]):a.className&&$rs.hasClass(a,"rssettings-button-gotobottom")&&rspkr.ui.focus(A)})},200):$rs.isArray(h)||setTimeout(function(){rspkr.ui.focus(h)},200);e();$rs.regEvent(window,"resize",e);"function"==typeof k&&k.apply(this,[l])},hide:function(a){for(;0<v.length;){var f=v.pop();f[0].tabIndex=f[1]}if(!("Explorer"==rs.c.data.browser.name&&
6==rs.c.data.browser.version))for(var a=document.querySelectorAll("body > *"),f=0,i;i=a[f];f++){var k=i.getAttribute("data-original-aria-hidden");k?(i.setAttribute("aria-hidden",k),i.removeAttribute("data-original-aria-hidden")):i.removeAttribute("aria-hidden")}r(a);q.style.display="none";l.style.display="none";$rs.unregEvent(window,"resize",e);$rs.unregEvent($rs.get("#rslightbox_closer"),"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(q,"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(document.body,
"keyup",b);if((a=document.documentElement)&&document.all)a.style.overflowX=a.style.overflowY="auto";rspkr.ui.updateFocus();rspkr.c.dispatchEvent("onSettingsClosed",window,[])},reposition:t}}();
