window.ReadSpeakerDefer={deferred:null,clickhandler:function(b){b=b||window.event;var d=b.target||b.srcElement;3===d.nodeType&&(d=d.parentNode);if(d!==document&&window.ReadSpeakerDefer.isRSLink(d))return window.ReadSpeakerDefer.deferred=d,(d=window.ReadSpeakerDefer.findRSParent(d))&&d.className&&!/rsdeferred/i.test(d.className)&&(d.className+=" rsdeferred"),window.ReadSpeakerJIT&&r.loadCore(),b.cancelBubble=!0,b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),!1},init:function(){this.RSDeferClick(document)},
isRSLink:function(b){return this.isRSParent(b.parentNode)||b.href&&-1<b.href.indexOf("readspeaker.com/cgi-bin/rsent")},isRSParent:function(b){return b?b.className&&-1<b.className.indexOf("rsbtn")||b.id&&"string"===typeof b.id&&-1<b.id.indexOf("readspeaker_button"):!1},findRSParent:function(b){for(;b.parentNode&&b.parentNode!==document&&(b=b.parentNode,"a"!=b.tagName.toLowerCase()||!this.isRSLink(b)););return b==document?void 0:b.parentNode},RSDeferClick:function(b){b.addEventListener?b.addEventListener("click",
this.clickhandler,!1):b.attachEvent?b.attachEvent("onclick",this.clickhandler):b.onclick=this.clickhandler}};window.ReadSpeakerDefer.init();
(function(b){var d,e={major:"2",minor:"5",update:"8",revision:"3798",prod:"embhl"},k=[],J=0,w=0,K=!1,x=[],L=0,m=[],M=!1,y=!1,T=0,C=!1,n=null,h="default",N=!1,z=[],O=!1,D="",E={},F=!1,G="",A=null,s=!1,H=function(a){if("string"==typeof a){a="ReadSpeaker."+a.replace("_",".");a=a.split(".");for(var f=b,c=0,d=a.length;c<d;c++)if(f)if(f[a[c]]){if(c==d-1)return f[a[c]];f=f[a[c]]}else break;else break;return!1}},Q=function(a,f){x.push(a);L++;f=f||[a];for(var c=0,d=f.length;c<d;c++)try{var e=H(f[c]);"function"==
typeof e.init&&e.init.apply(e,[])}catch(U){u("[rspkr] Could not load: "+f[c]+" | "+U,3)}L===w&&!0===K&&(u("[rspkr] All prod mods loaded. _domready = "+C,4),s&&b.ReadSpeaker.init(),c=function(){rspkr.Common.createShortcuts();rspkr.devt("onModsLoaded",b);rspkr.devt("onAfterModsLoaded",b);E.onAdapterReady?rspkr.devt("onReady",b):rspkr.evt("onAdapterReady",function(){rspkr.devt("onReady",b)});b.ReadSpeaker.ui.viewport={width:$rs.width(b),height:$rs.height(b)}},b.ReadSpeaker.Common.addEvent("onReady",
function(){P.executeCode();P.flush();if(A)a:{rspkr.log("[rspkr.startAutoplay] Id: "+A);var a=$rs.get(A);if($rs.isArray(a)&&0<a.length)a=a[0];else if($rs.isArray(a)&&0==a.length)break a;a=$rs.findIn(a,"a");if($rs.isArray(a)&&0<a.length)a=a[0];else if($rs.isArray(a)&&0==a.length)break a;b.readpage(a)}}),C?c():b.ReadSpeaker.Common.addEvent("onDOMReady",c))},R=function(){if(!y){s&&!F&&(document.getElementById("rsmod_Styles").href=G+"ReadSpeaker.Styles.css");for(var a in k)k.hasOwnProperty(a)&&(mod=a,
q.load({id:"req_"+mod,type:"text/javascript",src:"ReadSpeaker."+mod+".js",cb:function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("req_",""),a=a.replace("_","."),a=!1===k[a]?[a]:k[a],c;J++;for(var d=0,e=a.length;d<e;d++)x.push(a[d]),c=H(a[d]),"function"==typeof c.init&&c.init.apply(c,[]);J===Object.size(k)&&(b.ReadSpeaker.Common.addEvent("onModsLoaded",b.ReadSpeaker.pub.Config.setup),O=!0,a={id:"",type:"text/javascript",src:"",cb:function(){var a=
(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("rsmod_","");x.push(a);a=H(a);"function"==typeof a.init&&a.init.apply(a,[]);if(O&&b.ReadSpeaker.modmap&&!M){for(var a=b.ReadSpeaker.modmap,c=[],f=0,d="|",e=[],p=0,h=z.length;p<h;p++)if(c=a.products&&"function"==typeof a.products[z[p]]?a.products[z[p]]():null){for(var g=f=0,k=c.length;g<k;g++)-1===d.indexOf("|"+c[g][0]+c[g][1]+"|")&&(c[g][0].length&&(e[c[g][0]]=c[g][2],/text\/javascript/.test(c[g][1])&&(cb=function(){var a=
(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("rsmod_","");Q(a,e[a])}),q.load({id:"rsmod_"+c[g][0],type:c[g][1],src:"ReadSpeaker."+c[g][0]+("text/css"===c[g][1]?".css":".js"),cb:cb,async:!0})),"undefined"!==typeof c[g][1]&&/text\/javascript/.test(c[g][1])&&f++,d+=c[g][0]+c[g][1]+"|");w+=f}K=!0}}},c=b.ReadSpeaker.lib.Facade.currentLib().toLowerCase(),"rslib"==c?(a.id="rsmod_lib.RSLib",a.src="ReadSpeaker.lib.RSLib.js"):(a.id="rsmod_lib.Facade.adapter."+c,
a.src="ReadSpeaker.lib.Facade.adapter."+c+".js"),q.load(a))},async:!0}))}},S=function(){rspkr.log("[rspkr.updateBaseClass] Attempting to update..");for(var a=document.getElementsByTagName("div"),f=/\brsbtn\b/,c=0,d=a.length;c<d;c++)f.test(a[c].className)&&(a[c].className=a[c].className.replace(f,b.rsConf.ui.rsbtnClass));rspkr.log("[rspkr.updateBaseClass] Update successful!");Q("skinfile")};d={extract:function(a){if("string"==typeof a){var b={};a=a.split(/[;&]/);for(var c,d=0;d<a.length;d++)(c=a[d].split("="))&&
2==c.length&&(b[unescape(c[0])]=unescape(c[1]).replace(/\+/g," "));return b}return{}}};var P={isok:!0,executeCode:function(){this.isok=!0;if(!m.length)return!0;for(idx in m)if(m.hasOwnProperty(idx)&&"function"==typeof m[idx])try{m[idx].apply(b,[])}catch(a){this.isok=!1,rspkr.log("[rspkr.q] "+a,3)}},flush:function(){m=[]}},q={load:function(a){if("text/javascript"==a.type||"text/css"==a.type){a.src=n.path+a.src;var d=document.getElementsByTagName("head")[0],c=document.createElement("text/javascript"==
a.type?"script":"link"),p=[e.major,e.minor,e.update,e.revision].join(".");"function"==typeof a.cb&&(void 0!==c.onreadystatechange?c.onreadystatechange=function(){"complete"!=this.readyState&&"loaded"!=this.readyState||a.cb.apply(b)}:c.onload=a.cb);c.id=a.id.replace(".","_");c.type=a.type;"text/javascript"==a.type?(c.src=a.src+"?v="+p,a.async&&(c.async=!0)):(c.rel="stylesheet",c.href=a.src+"?v="+p);d.appendChild(c)}}},V=0,I={1:[],2:[],3:[],4:[],5:[],6:[]},t={1:{lbl:"Info",method:"log"},2:{lbl:"Warn",
method:"warn"},3:{lbl:"Err",method:"error"},4:{lbl:"AS",method:"log"},5:{lbl:"SW",method:"log"}},u=function(a,b){var c=D;b=b||1;I[b].push(a);if(c&&"string"===typeof c&&-1<c.indexOf(","+b+",")){c=t[b].lbl;try{console[t[b].method]&&console[t[b].method](V++ +". "+c+": "+a)}catch(d){}}},W=function(a){D=/^,[0-9,]*,$/.test(a)?a:","+a+","};Object.size=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};if(b.rsConf&&b.rsConf.params&&"string"===typeof b.rsConf.params&&b.rsConf.params)var v=
b.rsConf.params,l=v.split("?");else l=document.getElementsByTagName("script"),v=l[l.length-1].getAttribute("src"),l=v.split("?");if(/\?/i.test(v)&&1<l.length&&l[1].length){var G=v.replace(/[^\/]*$/,""),B;if(/rsdebug=rsdebug/i.test(document.location.href))try{B=","+document.location.href.split("?").pop().match(/rsdebug=rsdebug([^$|&]*)/i).pop()+","}catch(X){B=",3,"}else B="";D=B;n=d=d.extract(l[1]);h=d.skin||"default";z=d.pids.split(",");n.path=l[0].replace("ReadSpeaker.js","");k.Core=["Common","lib.Facade",
"modmap"];k["pub.Config"]=!1;A=d.autoplay;s=b.ReadSpeakerJIT="1"===d.jit;n.forceBasicMode&&"1"===n.forceBasicMode||document.attachEvent&&/MSIE/i.test(navigator.userAgent)&&(document.compatMode&&"backcompat"===document.compatMode.toLowerCase()||/MSIE 6\./i.test(navigator.userAgent))?(F=!0,q.load({id:"rsmod_Styles",type:"text/css",src:(n.skinPathBasic||"ReadSpeaker.Styles-Basic")+".css",cb:null})):(q.load({id:"rsmod_Styles",type:"text/css",src:"ReadSpeaker.Styles"+(s?"-Button":"")+".css",cb:null}),
"default"!==h&&!s&&(w++,q.load({id:"rsskin_"+h+"_style",type:"text/css",src:"skins/"+h+"/"+h+".css",cb:null}),q.load({id:"rsskin_"+h+"_js",type:"text/javascript",src:"skins/"+h+"/"+h+".js",cb:function(){"default"!==h&&y?S():N=!0},async:!0})));s||R()}else M=!0;d=new function(){this.meta={obj:e,version:[e.major,e.minor,e.update].join(".")+"_rev"+e.revision+"-"+e.prod};this.q=function(a){"function"==typeof a&&(E.onReady?a.apply(b,[]):m.push(a))};this.init=function(){y||(y=!0,document.addEventListener&&
document.removeEventListener("DOMContentLoaded",b.ReadSpeaker.init,!1),C=!0,b.ReadSpeaker.Common&&b.ReadSpeaker.Common.dispatchEvent("onDOMReady"),u("[rspkr] DOM Ready!"),N&&(u("[rspkr] Updating base class.",1),S()))};this.getLoadedMods=function(){return x};this.rsidCount=1E3;this.logcount=0;this.log=function(a,b){u(a,b||1)};this.showLog=function(a){a=a||"1";rspkr.log("[rspkr.printErrorLog]",1);a=(a||"3").split(",");for(var b=0;b<a.length;b++)if(I.hasOwnProperty(a[b])){var c=I[a[b]],d=a[b],d=parseInt(d)||
3,e=t[d].lbl;console.groupCollapsed&&console.groupCollapsed(e);for(e=0;e<c.length;e++)try{console[t[d].method]&&console[t[d].method](c[e])}catch(h){}console.groupCollapsed&&console.groupEnd()}};this.getID=function(){return"readspeaker"+T++};this.getVersion=function(){return this.meta.version};this.skin=h;this.displog=E;this.basicMode=F;this.params=n;this.setDebugLevel=W;this.baseUrl=G;this.loadCore=R;this.audio=null};b.ReadSpeaker=b.rs=b.rspkr=d})(window);
ReadSpeaker.enums={mime:{tjs:"text/javascript",tcss:"text/css",thtml:"text/html"}};(function(b){if(!window.ReadSpeakerJIT){var d=navigator.userAgent,e=/*@cc_on!@*/false,k=setTimeout;/mozilla/i.test(d)&&!/(compati)/.test(d)||/opera/i.test(d)||/webkit/i.test(d)?document.addEventListener("DOMContentLoaded",b,!1):e?function(){var d=document.createElement("doc:rdy");try{d.doScroll("left"),b()}catch(e){k(arguments.callee,0)}}():window.onload=b}})(ReadSpeaker.init);
